package com.leclowndu93150.thaumaturge;

import com.leclowndu93150.thaumaturge.api.aspect.AspectIndexAccess;
import com.leclowndu93150.thaumaturge.api.aura.AuraHelper;
import com.leclowndu93150.thaumaturge.api.aura.VisRelayHelper;
import com.leclowndu93150.thaumaturge.api.capability.KnowledgeAccess;
import com.leclowndu93150.thaumaturge.api.casters.FocusEngine;
import com.leclowndu93150.thaumaturge.api.entity.trait.MobTraits;
import com.leclowndu93150.thaumaturge.api.golems.GolemHelper;
import com.leclowndu93150.thaumaturge.api.items.GogglesAccess;
import com.leclowndu93150.thaumaturge.api.items.RechargeAccess;
import com.leclowndu93150.thaumaturge.api.recipe.ArcaneCraftCost;
import com.leclowndu93150.thaumaturge.api.recipe.ArcaneCraftingTransaction;
import com.leclowndu93150.thaumaturge.api.recipe.InfusionCraftingTransaction;
import com.leclowndu93150.thaumaturge.api.recipe.RegisterWorkbenchAuraSourcesEvent;
import com.leclowndu93150.thaumaturge.api.recipe.RegisterWorkbenchVisSourcesEvent;
import com.leclowndu93150.thaumaturge.api.recipe.ResearchGate;
import com.leclowndu93150.thaumaturge.api.research.pool.AspectPoolAccess;
import com.leclowndu93150.thaumaturge.api.research.scan.ScanningManager;
import com.leclowndu93150.thaumaturge.api.taint.TaintApi;
import com.leclowndu93150.thaumaturge.api.wands.WandAccess;
import com.leclowndu93150.thaumaturge.api.warp.WarpHelper;
import com.leclowndu93150.thaumaturge.compat.curio.ThaumaturgeCuriosCompat;
import com.leclowndu93150.thaumaturge.config.TaintConfigMigration;
import com.leclowndu93150.thaumaturge.config.ThaumaturgeClientConfig;
import com.leclowndu93150.thaumaturge.config.ThaumaturgeCommonConfig;
import com.leclowndu93150.thaumaturge.config.ThaumaturgeServerConfig;
import com.leclowndu93150.thaumaturge.content.aspect.AspectIndexBuilder;
import com.leclowndu93150.thaumaturge.content.aspect.AspectIndexHolder;
import com.leclowndu93150.thaumaturge.content.aura.AuraHelperBindings;
import com.leclowndu93150.thaumaturge.content.aura.relay.VisRelayNetwork;
import com.leclowndu93150.thaumaturge.content.aura.relay.VisRelayWorkbenchSource;
import com.leclowndu93150.thaumaturge.content.entity.trait.MobTraitBindings;
import com.leclowndu93150.thaumaturge.content.equipment.TTMaterials;
import com.leclowndu93150.thaumaturge.content.golem.GolemBindings;
import com.leclowndu93150.thaumaturge.content.infusion.InfusionCraftingTransactions;
import com.leclowndu93150.thaumaturge.content.item.BathSaltsEvents;
import com.leclowndu93150.thaumaturge.content.legacy.LegacyRegistryAliases;
import com.leclowndu93150.thaumaturge.content.research.ResearchManager;
import com.leclowndu93150.thaumaturge.content.research.pool.AspectPoolBindings;
import com.leclowndu93150.thaumaturge.content.research.scan.ScanBindings;
import com.leclowndu93150.thaumaturge.content.taint.TaintApiBindings;
import com.leclowndu93150.thaumaturge.content.wands.WandAccessBindings;
import com.leclowndu93150.thaumaturge.content.warp.WarpManager;
import com.leclowndu93150.thaumaturge.content.workbench.ArcaneCraftingTransactions;
import com.leclowndu93150.thaumaturge.content.workbench.WorkbenchPayment;
import com.leclowndu93150.thaumaturge.registry.*;
import com.leclowndu93150.thaumaturge.registry.TTIngredientTypes;
import com.leclowndu93150.thaumaturge.registry.TTParticles;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.ModList;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.loading.FMLPaths;
import net.neoforged.neoforge.common.NeoForge;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Mod(TTIds.MODID)
public final class Thaumaturge {
    public static final Logger LOGGER = LoggerFactory.getLogger(TTIds.MODID);

    public Thaumaturge(IEventBus modBus, ModContainer container) {
        NeoForge.EVENT_BUS.addListener(BathSaltsEvents::onItemExpire);
        NeoForge.EVENT_BUS.addListener(BathSaltsEvents::onEntityTick);
        TTFluidTypes.register(modBus);
        TTFluids.register(modBus);
        TTBlocks.register(modBus);
        TTMaterials.register(modBus);
        TTItems.register(modBus);
        TTFeatures.register(modBus);
        TTStructures.register(modBus);
        TTBlockEntities.register(modBus);
        TTEntities.register(modBus);
        TTMenus.register(modBus);
        TTRecipeTypes.register(modBus);
        TTRecipeSerializers.register(modBus);
        TTDataComponents.register(modBus);
        TTCreativeTabs.register(modBus);
        TTParticles.register(modBus);
        TTSounds.register(modBus);
        TTAttachments.register(modBus);
        TTDamageTypes.register(modBus);
        TTMobEffects.register(modBus);
        TTAttributes.register(modBus);
        TTChunkGenerators.register(modBus);
        TTBiomeModifierSerializers.register(modBus);
        TTPlacementModifiers.register(modBus);
        TTGolemTraits.register(modBus);
        TTMobTraits.register(modBus);
        TTFocusElements.register(modBus);
        TTGolemParts.register(modBus);
        TTWandParts.register(modBus);
        TTSeals.register(modBus);
        TTEntityDataSerializers.register(modBus);
        TTIngredientTypes.register(modBus);
        TTGolemAccessories.register();

        LegacyRegistryAliases.register(modBus);

        TaintConfigMigration.migrate(FMLPaths.CONFIGDIR.get().resolve(TTIds.MODID + "-common.toml"));
        container.registerConfig(ModConfig.Type.COMMON, ThaumaturgeCommonConfig.SPEC);
        container.registerConfig(ModConfig.Type.CLIENT, ThaumaturgeClientConfig.SPEC);
        container.registerConfig(ModConfig.Type.SERVER, ThaumaturgeServerConfig.SPEC);

        KnowledgeAccess.bind(player -> player.getData(TTAttachments.KNOWLEDGE));
        AspectIndexAccess.bind(AspectIndexHolder::get);
        AspectIndexBuilder.fireContributorEvent(modBus);
        WandAccess.bind(new WandAccessBindings());
        ArcaneCraftCost.bind(WorkbenchPayment::cost);
        ArcaneCraftingTransaction.bind(new ArcaneCraftingTransactions());
        InfusionCraftingTransaction.bind(new InfusionCraftingTransactions());
        RegisterWorkbenchVisSourcesEvent visSourcesEvent = new RegisterWorkbenchVisSourcesEvent();
        visSourcesEvent.register(new VisRelayWorkbenchSource());
        modBus.post(visSourcesEvent);
        WorkbenchPayment.registerSources(visSourcesEvent.sources());
        RegisterWorkbenchAuraSourcesEvent auraSourcesEvent = new RegisterWorkbenchAuraSourcesEvent();
        modBus.post(auraSourcesEvent);
        WorkbenchPayment.registerAuraSources(auraSourcesEvent.sources());
        AuraHelper.bind(new AuraHelperBindings());
        VisRelayHelper.bind(new VisRelayNetwork());
        TaintApi.bind(new TaintApiBindings());
        MobTraits.bind(new MobTraitBindings());
        WarpHelper.bind(new WarpManager.Bindings());
        ScanningManager.bind(new ScanBindings());
        GolemHelper.bind(new GolemBindings());
        AspectPoolAccess.bind(new AspectPoolBindings());
        ResearchGate.bind(ResearchManager::doesPassGate);
        RechargeAccess.bind(TTDataComponents.CHARGE);
        GogglesAccess.bind(() -> TTAttributes.VIS_DISCOUNT);
        FocusEngine.bindRegistry(TTFocusElements.registry());

        if (ModList.get().isLoaded(TTIds.CURIOS)) ThaumaturgeCuriosCompat.init(modBus);
    }
}
